# Generated by Django 4.1.1 on 2022-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('context', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schname', models.CharField(blank=True, max_length=100, null=True)),
                ('hist', models.CharField(blank=True, choices=[('jr', 'junior'), ('sr', 'senior'), ('gr', 'graduate')], default='junior', max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('shortdescription', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('techstack', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=50)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Specialskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Special skills',
            },
        ),
        migrations.CreateModel(
            name='Workexp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpname', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('shortdescription', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Work Exp',
            },
        ),
    ]
