# Generated by Django 4.0.6 on 2022-09-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialskills',
            name='Assignment',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='specialskills',
            name='Cycling',
            field=models.CharField(blank=True, choices=[('1-2 hours', '1-2 hours'), ('Less than 1 hour', 'Less than 1 hour'), ('None', 'None')], default='None', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='specialskills',
            name='Grooming',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Not done', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='specialskills',
            name='Journaling',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='specialskills',
            name='Workout',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30, null=True),
        ),
    ]
