# Generated by Django 4.0.6 on 2022-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_week_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='None', max_length=30, null=True),
        ),
    ]
