# Generated by Django 4.0.6 on 2022-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_week_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='day',
            new_name='Day',
        ),
        migrations.AddField(
            model_name='specialskills',
            name='Day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='None', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
